### ISSUE TITLE
Beskar Reinforced Plating not Triggering even if Attacker is in front arc

### ISSUE THREAD

**Issue by quall3** [Baledin/FlyCasual#15]
** Fly Casual Release Version**
Latest

**Describe the bug**
My (small base) Ship has Beskar Reinforced Plating equipped, Suffers a critical damage from an Attacker in its Front Arc, but when its dealt a faceup damage card, it is not asked to spend 1 or 2 Charges to be dealt Face down or discarded. (It does Work on a Large base however).

**To Reproduce**
1. Equip Beskar Reinforced Plating on a Fang fighter
2. Suffer a Critical Damage

**Expected behavior**
On being dealt a Face up damage card, there should be an Option to either spend 1 charge to be dealt the card face down or spend 2 charges to discard the damage card.

**Comment by Baledin** [comment]
The upgrade was checking for charges on the pilot/ship, not the upgrade and was therefore failing to correctly trigger if the pilot/ship did not have charges (I'm guessing that the large ships tested did have charges). Please let me know what large base ships/pilots you were testing with as I'd like to review and ensure that there aren't additional issues at work here.

Fixed in a96eac5.
