### ISSUE TITLE
Allow to disable points validation and/or XWS import [enhancement]

### ISSUE THREAD

**Issue by whittaker007** [Baledin/FlyCasual#75]
**Is your feature request related to a problem? Please describe.**

My biggest problem with FlyCasual is when I go to try out a list, the points for ships and upgrades are not up to date, resulting in not being able to even build the list. Now that we have multiple point systems between AMG and XWA (not to mention Legacy 2.0), the problem is compounded.

**Describe the solution you'd like**

Rather than attempt to implement all the different point systems and try keeping them up to date, a "simple" and flexible option would be to allow points restrictions to be turned off so that you can build any list regardless of whether it exceeds what is currently considered the "correct" points. 

That's Phase 1, just a checkbox in the UI for unrestricted building mode, and let the user add whatever they want.

Of course there can be other limitations besides points changes. Individual ships can have slots added and removed as part of a points change. So Phase 2 could be a preference toggle for "developer mode" which would allow you to add any upgrade slot to any ship. 

Phase 3 would be extending "developer mode" to modify ship stats and action bar.

But really Phase 1 would go a long way.

**Describe alternatives you've considered**

There's another alternative method I've considered that would address this issue, and that would be a list building mode based on pasting XWS formatted text. 

All the list builders currently in use are able to export lists in XWS format. So let the list builders handle the logic for points and list building restrictions and allow users to paste in their exported XWS. 

You could then use the XWS description of the list, the pilots and their upgrades and skip any validation (except perhaps unknown pilots).

You could maybe make lists imported by XWS read-only and unable to be edited if you want to skip the whole UI and validation stuff and if a user wants to make changes, they update their list in their app of choice and re-import the list.

**Comment by whittaker007** [comment]
Sorry, I'm not sure how to add the "Enhancement" tag.

**Comment by Baledin** [comment]
Removing point limits is already available under Options > Extras > No Squad Builder Limits. Regarding XWS loading, there is an import function (after selecting faction, go to Squad and Import) but allowing a free-for-all loading wouldn't work due to the behind the scenes functionality of the pilots--it's not as easy as saying "Has Han Solo's Pilot Ability." Fly Casual was never really intended for Home Brew like you're suggesting for Phase 2 however.

Also, if you see any ships that aren't correct as far as posted points go, please let me know. The reason I took over the repo is because Sandrem is involved in the Ukraine war and points weren't up-to-date. My intention is that points will be up within two weeks of posting and I've only missed that target once (excepting the first point update which was published before I took over the repo). I am currently working on a plan for allowing different a selection of points (XWA, AMG, old point lists, etc) but it's still in-progress.

I'm closing this issue as I believe that the requests are already in-place or out-of-scope for the project but if you feel that the options currently available don't meet your needs, let me know.
